<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIzNUXwX\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIzNUXwX/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIzNUXwX.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIzNUXwX\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIzNUXwX\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IzNUXwX',
    'container.build_id' => '3eb5a1cb',
    'container.build_time' => 1578079616,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIzNUXwX');
