<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6UgCpbc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6UgCpbc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6UgCpbc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6UgCpbc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6UgCpbc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6UgCpbc',
    'container.build_id' => '53ba4c9f',
    'container.build_time' => 1578073895,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6UgCpbc');
