<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBHcn6X1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBHcn6X1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBHcn6X1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBHcn6X1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBHcn6X1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BHcn6X1',
    'container.build_id' => 'e00e4be8',
    'container.build_time' => 1578076027,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBHcn6X1');
