<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ45TYxX\srcApp_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ45TYxX/srcApp_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerQ45TYxX.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevContainer::class, false)) {
    \class_alias(\ContainerQ45TYxX\srcApp_KernelDevContainer::class, srcApp_KernelDevContainer::class, false);
}

return new \ContainerQ45TYxX\srcApp_KernelDevContainer([
    'container.build_hash' => 'Q45TYxX',
    'container.build_id' => '957bd112',
    'container.build_time' => 1577911609,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ45TYxX');
